# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: WeStud.io Dev Center
email: westudio@wemanity.com
description: > # this means to ignore newlines until "baseurl:"
  WeStud.io Dev Center sets common rules for our developers to follow. It can be 
  coding style, processes, best practices, ...
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dev.westud.io/" # the base hostname & protocol for your site
twitter_username: westud_io
github_username:  we-studio

# Build settings
markdown: kramdown
